Repository OptimumCode/json-schema-validator, pull requests merged in 2024-08, with the labels that each got.

#175 Add FOSSA integration
  .github/workflows/fossa-analyze.yml
Labels: CI/CD, security, repository enhancement

#179 Fix gradle wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: fix, repository enhancement

#178 Support `wasm` target
  README.md
  json-schema-validator/build.gradle.kts
  json-schema-validator/src/commonMain/kotlin/io/github/optimumcode/json/schema/internal/formats/IdnHostnameFormatValidator.kt
  json-schema-validator/src/commonMain/kotlin/io/github/optimumcode/json/schema/internal/hostname/Normalizer.kt
  json-schema-validator/src/nonWasmJsMain/kotlin/io/github/optimumcode/json/schema/internal/hostname/Normalizer.nonWasmJs.kt
  json-schema-validator/src/wasmJsMain/kotlin/io/github/optimumcode/json/schema/internal/hostname/Normalizer.wasmJs.kt
  test-suites/build.gradle.kts
Labels: enhancement

#184 Correct PR workflow to work for PRs from worked repositories
  .fossa.yml
  .github/workflows/code-coverage-upload.yml
  .github/workflows/pr-compliance-check.yml
  .github/workflows/pull_request.yml
  .reviewdog.yml
Labels: CI/CD, fix, repository enhancement

#188 Migrate to karacteristics library for codepoint characteristics
  build.gradle.kts
  generator/build.gradle.kts
  generator/data/DerivedJoiningType.txt
  generator/data/README.md
  generator/data/rfc5895_appendix_b_1.txt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/Main.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/dump/DataDamper.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/dump/DerivedPropertiesLoader.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/dump/JoiningTypesLoader.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/dump/Util.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/generator/CategoryGenerator.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/generator/DerivedJoinigTypeGenerator.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/generator/DerivedPropertiesGenerator.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/generator/DirectionGenerator.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/generator/Util.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/graphql/GraphqlClient.kt
  generator/src/main/kotlin/io/github/optimumcode/unocode/generator/internal/model/Model.kt
  generator/src/main/resources/BidirectionalCharacterForClass.graphql
  generator/src/main/resources/BidirectionalClasses.graphql
  generator/src/main/resources/CharacterCategories.graphql
  generator/src/main/resources/CharactersForCategory.graphql
  gradle/libs.versions.toml
  json-schema-validator/build.gradle.kts
  json-schema-validator/src/commonMain/kotlin/io/github/optimumcode/json/schema/internal/formats/IdnHostnameFormatValidator.kt
  settings.gradle.kts
Labels: enhancement
